#line 2 "lexer.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 97
#define YY_END_OF_BUFFER 98
static yyconst short int yy_acclist[378] =
    {   0,
       98,   96,   97,   95,   96,   97,   94,   95,   97,   82,
       96,   97,   96,   97,   96,   97,   88,   96,   97,   81,
       96,   97,   96,   97,   76,   96,   97,   77,   96,   97,
       86,   96,   97,   85,   96,   97,   73,   96,   97,   84,
       96,   97,   80,   96,   97,   87,   96,   97,   43,   96,
       97,   43,   96,   97,   74,   96,   97,   70,   96,   97,
       89,   96,   97,   75,   96,   97,   90,   96,   97,   93,
       96,   97,   49,   96,   97,   49,   96,   97,   78,   96,
       97,   79,   96,   97,   91,   96,   97,   49,   96,   97,
       49,   96,   97,   49,   96,   97,   49,   96,   97,   49,

       96,   97,   49,   96,   97,   49,   96,   97,   49,   96,
       97,   49,   96,   97,   49,   96,   97,   49,   96,   97,
       49,   96,   97,   49,   96,   97,   49,   96,   97,   49,
       96,   97,   71,   96,   97,   92,   96,   97,   72,   96,
       97,   83,   96,   97,   69,   48,   56,   72,   64,   57,
       54,   62,   52,   63,   53,   46,    1,    2,   55,   47,
       42,   43,   43,   43,   79,   71,   78,   61,   66,   68,
       67,   60,   49,   58,   49,   49,   49,   49,   49,   49,
       49,   13,   49,   49,   49,   49,   49,   49,   19,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   59,   65,
       44,   46,    2,   46,   47,   47,   42,   43,   45,   41,
       51,   50,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   18,   49,   20,   49,   49,   49,   22,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   46,   46,
       47,   47,   45,   41,    4,   49,   49,    7,   49,    8,
       49,   49,   49,   49,   49,   14,   49,   15,   49,   49,
       49,   21,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   33,   49,   34,   49,   49,   49,

       49,   49,   39,   49,   49,   46,   47,    6,   49,    9,
       49,   10,   49,   49,   49,   16,   49,   17,   49,   49,
       49,   49,   49,   26,   49,   49,   49,   49,   49,   49,
       49,   49,   36,   49,   49,   49,   40,   49,   49,   49,
        5,   49,   49,   49,   25,   49,   27,   49,   28,   49,
       29,   49,   30,   49,   31,   49,   32,   49,   49,   49,
       49,   49,   12,   49,   49,   24,   35,   49,   49,   38,
       49,   11,   49,   23,   37,   49,    3
    } ;

static yyconst short int yy_accept[276] =
    {   0,
        1,    1,    1,    2,    4,    7,   10,   13,   15,   17,
       20,   23,   25,   28,   31,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   85,   88,   91,   94,   97,  100,  103,  106,
      109,  112,  115,  118,  121,  124,  127,  130,  133,  136,
      139,  142,  145,  146,  146,  147,  147,  147,  148,  149,
      150,  151,  151,  151,  152,  153,  154,  155,  156,  157,
      158,  159,  160,  161,  163,  163,  164,  164,  165,  166,
      167,  168,  169,  170,  171,  172,  173,  174,  174,  174,
      175,  176,  177,  178,  179,  180,  181,  182,  184,  185,

      186,  187,  188,  189,  191,  192,  193,  194,  195,  196,
      197,  198,  199,  200,  201,  202,  203,  204,  205,  206,
      207,  208,  209,  210,  211,  211,  212,  212,  213,  214,
      216,  216,  217,  219,  219,  220,  221,  222,  223,  224,
      225,  226,  227,  228,  229,  230,  231,  232,  233,  234,
      236,  238,  239,  240,  242,  243,  244,  245,  246,  247,
      248,  249,  250,  251,  252,  253,  254,  255,  256,  257,
      258,  259,  259,  259,  260,  260,  262,  262,  263,  264,
      265,  267,  268,  270,  272,  273,  274,  275,  276,  278,
      280,  281,  282,  284,  285,  286,  287,  288,  289,  290,

      291,  292,  293,  294,  295,  297,  299,  300,  301,  302,
      303,  305,  306,  306,  306,  308,  310,  312,  314,  315,
      316,  318,  320,  321,  322,  323,  324,  326,  327,  328,
      329,  330,  331,  332,  333,  335,  336,  337,  339,  339,
      340,  341,  343,  344,  345,  347,  349,  351,  353,  355,
      357,  359,  360,  361,  362,  362,  363,  365,  366,  366,
      367,  369,  370,  372,  372,  374,  374,  375,  377,  377,
      377,  377,  377,  378,  378
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   37,   30,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   30,   47,   48,   49,   50,
       51,   52,   30,   53,   54,   55,   56,   57,   58,   33,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    5,
        5,    5,    5,    1,    1,    1,    1,    4,    4,    4,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[281] =
    {   0,
        0,    0,  418,  419,  419,  419,  393,   59,  370,   42,
       59,  380,  419,  419,  390,   55,  419,   54,   52,   62,
       78,   57,  388,  419,   79,  388,   57,  419,    0,   86,
      419,  419,  387,   40,   70,   65,   64,   79,   79,  359,
       81,   48,  367,   86,   80,  358,   89,  362,  419,   66,
      419,  419,  419,  118,  419,  403,  355,  419,  419,  419,
      419,  126,  135,  419,  419,  419,  419,  419,  123,  419,
        0,  419,  127,  157,  143,  136,    0,  162,  419,  419,
      419,  380,  419,  419,  419,  379,    0,  143,  367,  419,
      350,  358,  345,  360,  359,  346,  352,    0,  340,  337,

      344,  340,  337,    0,  334,  338,  332,  328,  339,  345,
      328,  331,  104,  134,  335,  334,  323,  326,  137,  324,
      330,  329,  419,  419,  334,  419,  181,  419,    0,  183,
      201,  419,  176,  203,  208,  198,  419,  419,  325,  334,
      329,  317,  315,  179,  330,  325,  317,  311,  326,    0,
        0,  319,  316,    0,  304,  312,  303,  305,  307,  314,
      300,  104,  299,  299,  310,  309,  299,  303,  293,  306,
      298,  297,  216,  221,  228,  419,  238,  241,  419,  231,
        0,  297,    0,    0,  289,  287,  295,  284,    0,    0,
      297,  283,    0,  280,  298,  289,  281,  278,  290,  280,

      284,  279,  288,  287,    0,    0,  285,  275,  272,  254,
        0,  259,  244,  246,  254,    0,    0,    0,  249,  250,
        0,    0,  254,  240,  254,  243,    0,  251,  248,  250,
      244,  227,  236,  238,    0,  227,  238,    0,  214,  197,
      190,    0,  201,  217,    0,    0,    0,    0,    0,    0,
        0,  173,  167,  158,  156,  154,    0,  247,  257,  419,
        0,  145,    0,  178,    0,  265,  419,    0,  269,  167,
      131,   81,  419,  419,  302,  307,  309,  314,   69,  319
    } ;

static yyconst short int yy_def[281] =
    {   0,
      274,    1,  274,  274,  274,  274,  274,  275,  274,  274,
      274,  276,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  277,  277,
      274,  274,  274,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  274,  274,
      274,  274,  274,  275,  274,  275,  274,  274,  274,  274,
      274,  276,  276,  274,  274,  274,  274,  274,  274,  274,
      278,  274,  274,  274,  274,  274,  279,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  277,  275,  276,  274,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,

      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  274,  274,  274,  274,  274,  274,  278,  274,
      274,  274,  274,  274,  274,  279,  274,  274,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,

      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  274,  274,  274,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  274,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  274,  277,  277,  277,  274,  274,
      277,  277,  277,  274,  277,  274,  274,  277,  274,  280,
      280,  274,  274,    0,  274,  274,  274,  274,  274,  274
    } ;

static yyconst short int yy_nxt[484] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       30,   29,   29,   31,    4,   32,   33,   29,   34,   35,
       36,   37,   38,   29,   29,   39,   29,   40,   29,   41,
       29,   42,   43,   44,   45,   46,   47,   48,   29,   29,
       49,   50,   51,   52,   55,   58,   59,   60,   65,   67,
       69,   69,  136,   73,   70,   78,   78,   68,   66,   71,
       85,   86,   61,  273,   75,   72,   80,   76,   76,  123,
       91,   88,   92,   56,   73,   89,   74,   74,   75,   81,

      109,   82,   83,  110,   76,   75,   97,   93,   76,   76,
       77,   99,   76,  100,   94,   98,  101,   95,  107,   75,
       96,  104,  108,   55,  116,   76,  102,  124,  105,  103,
      112,  113,  117,   76,  120,  126,  272,  274,  118,  121,
      114,   69,   69,  115,   62,  130,  130,  159,   55,  202,
      127,  128,   56,  128,  131,  132,  134,  132,  134,  203,
       63,  135,  135,  160,  127,  128,   76,   76,  131,  132,
      128,  161,  272,   73,  132,   74,   74,   56,   73,  269,
       78,   78,  167,   76,   75,  268,  162,  133,  133,   75,
      168,   76,   76,   76,  173,  265,  173,  264,   75,  174,

      174,  130,  130,   75,  133,  263,  133,  133,  262,   76,
      175,  176,  133,  176,  177,  261,  177,   76,  259,  178,
      178,  135,  135,  133,  175,  176,  135,  135,  180,  180,
      176,  133,  186,  187,  174,  174,  179,  260,  179,  174,
      174,  214,  258,  214,  257,  180,  215,  215,  266,  128,
      179,  128,  256,  180,  255,  179,  178,  178,  259,  178,
      178,  180,  180,  128,  215,  215,  266,  267,  128,  132,
      269,  132,  215,  215,  270,  254,  253,  260,  180,  252,
      251,  250,  176,  132,  176,  267,  180,  249,  132,  248,
      247,  246,  245,  244,  243,  242,  176,  241,  240,  239,

      238,  176,   54,   54,   54,   54,   54,   62,   62,  237,
       62,   62,   87,   87,  129,  236,  129,  129,  129,  271,
      271,  271,  271,  271,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  220,
      219,  218,  217,  216,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  185,  184,
      183,  182,  181,  172,  171,  170,  169,  166,  165,  164,
      163,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  140,

      139,   63,  138,  137,  125,  274,  122,  119,  111,  106,
       90,   84,   79,   64,   63,   57,   53,  274,    3,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274
    } ;

static yyconst short int yy_chk[484] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,   10,   10,   11,   16,   18,
       19,   19,  279,   22,   20,   22,   22,   18,   16,   20,
       27,   27,   11,  272,   22,   20,   25,   22,   22,   50,
       34,   30,   34,    8,   21,   30,   21,   21,   22,   25,

       42,   25,   25,   42,   22,   21,   36,   35,   21,   21,
       21,   37,   22,   37,   35,   36,   38,   35,   41,   21,
       35,   39,   41,   54,   45,   21,   38,   50,   39,   38,
       44,   44,   45,   21,   47,   62,  271,   63,   45,   47,
       44,   69,   69,   44,   63,   73,   73,  113,   88,  162,
       69,   69,   54,   69,   73,   73,   75,   73,   75,  162,
       62,   75,   75,  113,   69,   69,   76,   76,   73,   73,
       69,  114,  270,   74,   73,   74,   74,   88,   78,  264,
       78,   78,  119,   76,   74,  262,  114,   74,   74,   78,
      119,   76,   78,   78,  127,  256,  127,  255,   74,  127,

      127,  130,  130,   78,   74,  254,  133,  133,  253,   78,
      130,  130,   74,  130,  131,  252,  131,   78,  244,  131,
      131,  134,  134,  133,  130,  130,  135,  135,  136,  136,
      130,  133,  144,  144,  173,  173,  135,  244,  135,  174,
      174,  175,  243,  175,  241,  136,  175,  175,  258,  174,
      135,  174,  240,  136,  239,  135,  177,  177,  259,  178,
      178,  180,  180,  174,  214,  214,  266,  258,  174,  178,
      269,  178,  215,  215,  269,  237,  236,  259,  180,  234,
      233,  232,  215,  178,  215,  266,  180,  231,  178,  230,
      229,  228,  226,  225,  224,  223,  215,  220,  219,  213,

      212,  215,  275,  275,  275,  275,  275,  276,  276,  210,
      276,  276,  277,  277,  278,  209,  278,  278,  278,  280,
      280,  280,  280,  280,  208,  207,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  192,  191,  188,
      187,  186,  185,  182,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  163,  161,  160,  159,  158,  157,  156,
      155,  153,  152,  149,  148,  147,  146,  145,  143,  142,
      141,  140,  139,  125,  122,  121,  120,  118,  117,  116,
      115,  112,  111,  110,  109,  108,  107,  106,  105,  103,
      102,  101,  100,   99,   97,   96,   95,   94,   93,   92,

       91,   89,   86,   82,   57,   56,   48,   46,   43,   40,
       33,   26,   23,   15,   12,    9,    7,    3,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "minicpp.lex"
#define INITIAL 0
#line 10 "minicpp.lex"
#include <stdio.h>

#include <string>
#include <stack>

#include "type.h"
#include "SyntaxTree.h"
#include "SourceManager.h"
#include "ErrorManager.h"

#include "minicpp.cpp.h"

#define SM SourceManager::GetSingleton() 

bool handleEof();
void handleInclude();
void eatMultilineComment();

#include "lexer.h"
#define   SKIP_YYWRAP		    1
#define   YY_NEVER_INTERACTIVE	1

struct includeinfo_t
{
  YY_BUFFER_STATE buf;
  int line;
  std::string filename;
};

std::stack<includeinfo_t> Files;

#line 643 "lexer.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 45 "minicpp.lex"

#line 792 "lexer.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 275 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 419 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 46 "minicpp.lex"
{ eatMultilineComment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 47 "minicpp.lex"
{ SM.incrementLineNumber(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 48 "minicpp.lex"
{ handleInclude(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "minicpp.lex"
{ return(BOOL); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 50 "minicpp.lex"
{ return(NATIVE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "minicpp.lex"
{ return(BREAK); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 52 "minicpp.lex"
{ return(CASE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 53 "minicpp.lex"
{ return(CHAR); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 54 "minicpp.lex"
{ return(CLASS); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 55 "minicpp.lex"
{ return(CONST); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 56 "minicpp.lex"
{ return(CONTINUE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 57 "minicpp.lex"
{ return(DEFAULT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 58 "minicpp.lex"
{ return(DO); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 59 "minicpp.lex"
{ return(ELSE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 60 "minicpp.lex"
{ return(ENUM); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 61 "minicpp.lex"
{ return(FALSE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 62 "minicpp.lex"
{ return(FLOAT); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 63 "minicpp.lex"
{ return(FOR); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 64 "minicpp.lex"
{ return(IF); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 65 "minicpp.lex"
{ return(INT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 66 "minicpp.lex"
{ return(LONG); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 67 "minicpp.lex"
{ return(NEW); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 68 "minicpp.lex"
{ return(PRIVATE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 69 "minicpp.lex"
{ return(PUBLIC); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 70 "minicpp.lex"
{ return(RETURN); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 71 "minicpp.lex"
{ return(SHORT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 72 "minicpp.lex"
{ return(SIGNED); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 73 "minicpp.lex"
{ return(SIZEOF); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 74 "minicpp.lex"
{ return(STATIC); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 75 "minicpp.lex"
{ return(STRING); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 76 "minicpp.lex"
{ return(STRUCT); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 77 "minicpp.lex"
{ return(SWITCH); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 78 "minicpp.lex"
{ return(THIS); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 79 "minicpp.lex"
{ return(TRUE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 80 "minicpp.lex"
{ return(TYPEDEF); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 81 "minicpp.lex"
{ return(UNION); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 82 "minicpp.lex"
{ return(UNSIGNED); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 83 "minicpp.lex"
{ return(VIRTUAL); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 84 "minicpp.lex"
{ return(VOID); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 85 "minicpp.lex"
{ return(WHILE); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 87 "minicpp.lex"
{ 
                         int i;
                         //hex
                         sscanf(yytext,"%x",&i);
                         yylval.intval = i;                         
                         return(INT_CONSTANT);
                       }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 94 "minicpp.lex"
{ 
                         int i;
                         //octal
                         sscanf(yytext,"%o",&i);
                         yylval.intval = i;
                         return(INT_CONSTANT);                          
                       }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 101 "minicpp.lex"
{ 
                         int i;
                         //decimal
                         sscanf(yytext,"%d",&i);
                         yylval.intval = i;
                         return(INT_CONSTANT);                          
                       }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 109 "minicpp.lex"
{                          
                         yylval.name = yytext;
                         return(STRING_LITERAL); 
                       }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 114 "minicpp.lex"
{ 
                         float f;
                         sscanf(yytext,"%f",&f);
                         yylval.realval = f;
                         
                         return(FLOAT_CONSTANT); 
                       }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 121 "minicpp.lex"
{ 
                         float f;
                         sscanf(yytext,"%f",&f);
                         yylval.realval = f;
                         return(FLOAT_CONSTANT); 
                       }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 127 "minicpp.lex"
{ 
                         float f;
                         sscanf(yytext,"%f",&f);
                         yylval.realval = f;
                         return(FLOAT_CONSTANT); 
                       }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 134 "minicpp.lex"
{                          
                         yylval.name = yytext;
                         return(STRING_LITERAL); 
                       }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 138 "minicpp.lex"
{ 
                         return(SM.checkType(yylval.intval));
                       }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 143 "minicpp.lex"
{ return(RIGHT_ASSIGN); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 144 "minicpp.lex"
{ return(LEFT_ASSIGN); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 145 "minicpp.lex"
{ return(ADD_ASSIGN); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 146 "minicpp.lex"
{ return(SUB_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 147 "minicpp.lex"
{ return(MUL_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 148 "minicpp.lex"
{ return(DIV_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 149 "minicpp.lex"
{ return(MOD_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 150 "minicpp.lex"
{ return(AND_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 151 "minicpp.lex"
{ return(XOR_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 152 "minicpp.lex"
{ return(OR_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 153 "minicpp.lex"
{ return(RIGHT_OP); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 154 "minicpp.lex"
{ return(LEFT_OP); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 155 "minicpp.lex"
{ return(INC_OP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 156 "minicpp.lex"
{ return(DEC_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 157 "minicpp.lex"
{ return(AND_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 158 "minicpp.lex"
{ return(OR_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 159 "minicpp.lex"
{ return(LE_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 160 "minicpp.lex"
{ return(GE_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 161 "minicpp.lex"
{ return(EQ_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 162 "minicpp.lex"
{ return(NE_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 163 "minicpp.lex"
{ return(';'); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 164 "minicpp.lex"
{ return('{'); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 165 "minicpp.lex"
{ return('}'); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 166 "minicpp.lex"
{ return(','); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 167 "minicpp.lex"
{ return(':'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 168 "minicpp.lex"
{ return('='); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 169 "minicpp.lex"
{ return('('); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 170 "minicpp.lex"
{ return(')'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 171 "minicpp.lex"
{ return('['); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 172 "minicpp.lex"
{ return(']'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 173 "minicpp.lex"
{ return('.'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 174 "minicpp.lex"
{ return('&'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 175 "minicpp.lex"
{ return('!'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 176 "minicpp.lex"
{ return('~'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 177 "minicpp.lex"
{ return('-'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 178 "minicpp.lex"
{ return('+'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 179 "minicpp.lex"
{ return('*'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 180 "minicpp.lex"
{ return('/'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 181 "minicpp.lex"
{ return('%'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 182 "minicpp.lex"
{ return('<'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 183 "minicpp.lex"
{ return('>'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 184 "minicpp.lex"
{ return('^'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 185 "minicpp.lex"
{ return('|'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 186 "minicpp.lex"
{ return('?'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 188 "minicpp.lex"
{ SM.incrementLineNumber(); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 189 "minicpp.lex"
{ }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 190 "minicpp.lex"
{ if (!handleEof()) return 0; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 191 "minicpp.lex"
{ /* ignore bad characters */ }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 193 "minicpp.lex"
ECHO;
	YY_BREAK
#line 1414 "lexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 275 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 275 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 274);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 193 "minicpp.lex"


void eatMultilineComment()
{
   register int c; 
   for ( ; ; ) 
   { 
      while(1)
	  {
	     c = yyinput(); if (c == '\n') SM.incrementLineNumber();
		 if (c == '*' || c == EOF) break;
	  }      
      if ( c == '*' ) 
      { 
	     while ( (c = yyinput()) == '*' ); 
		 if (c == '\n') SM.incrementLineNumber();
		 if ( c == '/' ) 
            break; /* found the end */ 
      } 
	  if ( c == EOF ) 
      { 
	     printf( "Trovato EOF in commento!\n" ); 
		 exit(1);
         break; 
      } 
   } 
}

bool handleEof()
{
   if (Files.empty()) return false;
   
   yy_delete_buffer(YY_CURRENT_BUFFER);
   yy_switch_to_buffer(Files.top().buf);
   SM.setCurrentLineNumber(Files.top().line + 1);
   SM.setCurrentFile(Files.top().filename);

   Files.pop();
      
   return true;   
}

void handleInclude()
{
   includeinfo_t ii;
   ii.buf = YY_CURRENT_BUFFER;
   ii.line = SM.getCurrentLineNumber();
   ii.filename = SM.getCurrentFile();
   Files.push(ii);   

   std::string filename = SM.getIncludeFile(yytext);
   yyin = fopen(filename.c_str(), "r");
   if (!yyin)
   {
      std::string error = "Impossibile aprire il file include: " + filename;
      ErrorManager::GetSingleton().logAndRaise(error.c_str());
   }
   
   SM.setCurrentFile(filename);
   yy_switch_to_buffer(yy_create_buffer(yyin, YY_BUF_SIZE));
   BEGIN(INITIAL);
}

void lexer::openFile(const std::string& filename)
{
  yyin = fopen(filename.c_str(), "r");
  SM.setCurrentFile(filename);
};

//hacks
int yywrap()
{
	return(1);
}

int isatty(int i)
{
  return 0;
}
